# Push Helm Chart to helm-charts-registry
name: Release  Helm Chart
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: erwin-portal-ldap-image-helm-chart
  cancel-in-progress: true

jobs:
  scan_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@5
    permissions:
      contents: read

  release_helm:
    needs: scan_helm
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@7
    secrets: inherit
    with:
      chart_name: "erwin-portal-ldap"
      helm_chart_version_generation: specified 
      image_tag_generation: specified 
      helm_chart_version: "${{ github.ref_name }}"
      image_tag: "${{ github.ref_name }}"